### PR TITLE
feat: 增加logcat日志下载保存，修改按钮的type

### PR DESCRIPTION
**Pull request by gzhtest**
> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [x] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [x] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [x] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [x] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### CODE REVIEW

**Comment by ZhouYixun** [comment]
有预览截图吗

**Comment by gzhtest** [comment]
2833675421
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonicCloudOrg/sonic-client-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月28日(星期三) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonicCloudOrg/sonic-client-web] feat: 增加logcat日志下载保存，修改按钮的type (PR #294)





 
有预览截图吗

**Comment by gzhtest** [comment]
> 有预览截图吗
image
image

**Review by ZhouYixun — APPROVED** [review]
mg

**Pull request merged**
